### PR TITLE
Fix broken helm logo

### PR DESCRIPTION
**Pull request by jdolitsky**

### CODE REVIEW

**Review by SteveLasker — APPROVED** [review]
LGTM

**Comment by mikebrow** [comment]
@jdolitsky bot is checking for DCO

**Comment by SteveLasker** [comment]
@jdolitsky, can you fix the signing so we can merge?

**Comment by jdolitsky** [comment]
@mikebrow @SteveLasker - done

**Comment by SteveLasker** [comment]
Thanks @jdolitsky
@mikebrow, any idea why it says approval required by 2 of;, and we have 2 approvals indicated above?

**Review by mikebrow — APPROVED** [review]

**Review by SteveLasker — APPROVED** [review]
LGTM

**Pull request merged**
