### PR TITLE
MAINTAINERS: not a markdown list

### PR DESCRIPTION
**Pull request by vbatts**
Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

### CODE REVIEW

**Comment by SteveLasker** [comment]
Merged into PR #19

**Comment by vbatts** [comment]
oh weird. How ever you did this, it does not preserve my commit in the git history at all.
Not sure that is ideal.

**Comment by SteveLasker** [comment]
to be fair, I cheated... After nominating Joey, I noticed additional PRs, including this one. Rather than wrestle git-merge semantics, I just changed the 4 `-`'s to `+`'s in my PR.
Did you want more credit for contribution :)

**Comment by vbatts** [comment]
i like git history :-)

**Pull request closed without merging**
