### PR TITLE
Updated Helm mediaType

### PR DESCRIPTION
**Pull request by sabre1041**
Updated mediaType for Helm

### CODE REVIEW

**Comment by dlorenc** [comment]
Nice!

**Comment by sudo-bmitch** [comment]
Is there an associated PR on Helm itself to use these? If so, it would be good to link that here.

**Comment by sabre1041** [comment]
@sudo-bmitch Over time, there have been slow changes. Here are a few of the changes:

* https://github.com/helm/helm/pull/5719

**Comment by scottrigby** [comment]
Thanks @sabre1041 

@sudo-bmitch Since that PR, current location in code is here:
https://github.com/helm/helm/blob/main/pkg/registry/constants.go#L27

**Review by sudo-bmitch — APPROVED** [review]

**Review by mikebrow — APPROVED** [review]
LGTM

**Review by SteveLasker — APPROVED** [review]
Thanks @sabre1041, awesome to see Helm finalize the OCI support

**Pull request merged**
